services:
    ebank-ms-discovery-service:
      build: ./discovery-service
      container_name: ebank-ms-discovery-service
      ports:
        - '8761:8761'
      expose:
        - '8761'
      healthcheck:
        test: ["CMD","curl","-f", "http://localhost:8761/actuator/health"]
        interval: 10s
        retries: 5
    ebank-ms-config-service:
      build: ./config-service
      container_name: ebank-ms-config-service
      ports:
        - '9999:9999'
      expose:
        - '9999'
      healthcheck:
        test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
        interval: 10s
        retries: 5
      environment:
        - DISCOVERY_SERVICE_URL=http://ebank-ms-discovery-service:8761/eureka
      depends_on:
        ebank-ms-discovery-service:
          condition: service_healthy
    ebank-ms-customer-service:
      build: ./customer-service
      container_name: ebank-ms-customer-service
      ports:
        - '8081:8081'
      expose:
        - '8081'
      healthcheck:
        test: [ "CMD","curl","-f", "http://localhost:8081/actuator/health" ]
        interval: 10s
        retries: 5
      environment:
        - DISCOVERY_SERVICE_URL=http://ebank-ms-discovery-service:8761/eureka
        - CONFIG_SERVICE=http://ebank-ms-config-service:9999
      depends_on:
        ebank-ms-config-service:
          condition: service_healthy
    ebank-ms-account-service:
      build: ./account-service
      container_name: ebank-ms-account-service
      ports:
        - '8082:8082'
      expose:
        - '8082'
      environment:
        - DISCOVERY_SERVICE_URL=http://ebank-ms-discovery-service:8761/eureka
        - CONFIG_SERVICE=http://ebank-ms-config-service:9999
      depends_on:
        ebank-ms-customer-service:
          condition: service_healthy
    ebank-ms-gateway-service:
      build: ./gateway-service
      container_name: ebank-ms-gateway-service
      ports:
        - '8888:8888'
      expose:
        - '8888'
      environment:
        - DISCOVERY_SERVICE_URL=http://ebank-ms-discovery-service:8761/eureka
        - CONFIG_SERVICE=http://ebank-ms-config-service:9999
      depends_on:
        ebank-ms-discovery-service:
          condition: service_healthy
        ebank-ms-config-service:
          condition: service_healthy