server:
  port: 8888

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8081/  # Ensure this points to the correct microservice
            predicates:
              - Path=/customers/**         # Ensure this matches the intended path
          - id: r2
            uri: http://localhost:8082/
            predicates:
              - Path=/accounts/**


  application:
    name: gateway-service
